Assignment_AppDev/Models/Trainer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Assignment_AppDev.Models
{
    public class Trainer
    {
		public int ID { get; set; }		

		[DisplayName("Trainer ID")]
		[Required]
		public string TrainerID { get; set; }
		
		[DisplayName(" Name")]
		public string Name { get; set; }
		
		[DisplayName("Address")]
		public string Address { get; set; }
		public int Age { get; set; }
		public int Phone { get; set; }
		
		public ApplicationUser Trainers { get; set; }
	}
}

Assignment_AppDev/ViewModels/TrainerViewModel.cs
using Assignment_AppDev.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Assignment_AppDev.ViewModels
{
    public class TrainerViewModel
    {
        public Trainer Trainer { get; set; }
        public IEnumerable<ApplicationUser> Trainers { get; set; }
    }
}

Assignment_AppDev/Controllers/TrainersController.cs
using Assignment_AppDev.Models;
using Assignment_AppDev.Utils;
using Assignment_AppDev.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASM_AppDevDD.Controllers
{
    public class TrainersController : Controller
    {
        // GET: Trainers
        private ApplicationDbContext _context;
        public TrainersController()
        {
            _context = new ApplicationDbContext();
        }

        [HttpGet]
        [Authorize(Roles = "TrainingStaff, Trainer")]
        public ActionResult Index()
        {
            if (User.IsInRole("TrainingStaff"))
            {
                var viewTrainer = _context.Trainers.Include(a => a.Trainers).ToList();
                return View(viewTrainer);
            }
            if (User.IsInRole("Trainer"))
            {
                var trainerId = User.Identity.GetUserId();
                var trainerVM = _context.Trainers.Where(te => te.TrainerID == trainerId).ToList();
                return View(trainerVM);
            }
            return View("Index");
        }
        [HttpGet]
        public ActionResult Details(int id)
        {
            var trainer = _context.Trainers.SingleOrDefault(t => t.ID == id);
            if (trainer == null)
            {
                return HttpNotFound();
            }

            return View(trainer);
        }
        [HttpGet]
        [Authorize(Roles = "TrainingStaff")]
        public ActionResult Create()
        {
            //Get Account Trainer
            var userInDb = (from r in _context.Roles where r.Name.Contains("Trainer") select r).FirstOrDefault();
            var users = _context.Users.Where(x => x.Roles.Select(y => y.RoleId).Contains(userInDb.Id)).ToList();
            var trainerUser = _context.Trainers.ToList();

            var viewModel = new TrainerViewModel
            {
                Trainers = users,
                Trainer = new Trainer()
            };
            return View(viewModel);
        }
        [HttpPost]
        [Authorize(Roles = "TrainingStaff")]
        public ActionResult Create(TrainerViewModel trainerrr)
        {
            var trainerinDb = (from te in _context.Roles where te.Name.Contains("Trainer") select te).FirstOrDefault();
            var trainerUser = _context.Users.Where(u => u.Roles.Select(us => us.RoleId).Contains(trainerinDb.Id)).ToList();
            try
            {
                _context.Trainers.Add(trainerrr.Trainer);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                TrainerViewModel trainerUserView = new TrainerViewModel()
                {
                    Trainers = trainerUser,
                    Trainer = trainerrr.Trainer
                };

                return View(trainerUserView);
            }
        }
            //    var trainerinDb = (from te in _context.Roles where te.Name.Contains("Trainer") select te).FirstOrDefault();
            //    var trainerUser = _context.Users.Where(u => u.Roles.Select(us => us.RoleId).Contains(trainerinDb.Id)).ToList();
            //    if (ModelState.IsValid)
            //    {

            //        var checkTrainerExist = _context.Trainers.Include(t => t.Trainers).Where(t => t.Trainers.Id == trainerrr.Trainer.TrainerID);
            //        if (checkTrainerExist.Count() > 0) //list ID comparison, if count == 0. jump to else
            //        {
            //            ModelState.AddModelError("", "Trainer Already Exists.");
            //        }
            //        else
            //        {
            //            _context.Trainers.Add(trainerrr.Trainer);
            //            _context.SaveChanges();
            //            return RedirectToAction("Index");
            //        }
            //    }
            //    TrainerViewModel trainerUserView = new TrainerViewModel()
            //    {
            //        Trainers = trainerUser,
            //        Trainer = trainerrr.Trainer
            //    };
            //    return View(trainerUserView);
            //}



            [HttpGet]
        [Authorize(Roles = "TrainingStaff")]
        public ActionResult Delete(int id)
        {
            var todo = _context.Trainers.SingleOrDefault(t => t.ID == id);
            if (todo == null)
            {
                return HttpNotFound();
            }

            _context.Trainers.Remove(todo);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
        [HttpGet]
        [Authorize(Roles = "TrainingStaff, Trainer")]
        public ActionResult Edit(int id)
        {
            var trainer = _context.Trainers.SingleOrDefault(t => t.ID == id);
            if (trainer == null)
            {
                return HttpNotFound();
            }

            return View(trainer);
        }
        [HttpPost]
        [Authorize(Roles = "TrainingStaff, Trainer")]
        public ActionResult Edit(Trainer model)
        {
            var trainerDb = _context.Trainers.SingleOrDefault(t => t.TrainerID == model.TrainerID);
            if (trainerDb == null)
            {
                return HttpNotFound();
            }

            trainerDb.TrainerID = model.TrainerID;
            trainerDb.Name = model.Name;
            trainerDb.Age = model.Age;
            trainerDb.Address = model.Address;
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
       
    }
}

Assignment_AppDev/Views/Trainers/Create.cshtml
@model Assignment_AppDev.ViewModels.TrainerViewModel
@{
    ViewBag.Title = "Create";
}

<h2>Create New Trainer</h2>
@Html.AntiForgeryToken()
@Html.ValidationSummary(false, "", new { @class = "text-success" })
@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(t => t.Trainer.TrainerID)
        @Html.DropDownListFor(tp => tp.Trainer.TrainerID,
        new SelectList(Model.Trainers, "ID", "UserName"), "",
        new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(t => t.Trainer.Name)
        @Html.TextBoxFor(t => t.Trainer.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(t => t.Trainer.Name)
    </div>
    <div class="form-group">
        @Html.LabelFor(t => t.Trainer.Address)
        @Html.TextBoxFor(t => t.Trainer.Address, new { @class = "form-control" })
        @Html.ValidationMessageFor(t => t.Trainer.Address)
    </div>
    <div class="form-group">
        @Html.LabelFor(t => t.Trainer.Age)
        @Html.TextBoxFor(t => t.Trainer.Age, new { @class = "form-control" })
        @Html.ValidationMessageFor(t => t.Trainer.Age)
    </div>
    <div class="form-group">
        @Html.LabelFor(t => t.Trainer.Phone)
        @Html.TextBoxFor(t => t.Trainer.Phone, new { @class = "form-control" })
        @Html.ValidationMessageFor(t => t.Trainer.Phone)
    </div>

    <button type="submit" class="btn btn-default">Create</button>
}
@Html.ActionLink("Back", "Index")

Assignment_AppDev/Views/Trainers/Details.cshtml
@model Assignment_AppDev.Models.Trainer
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
@Html.ActionLink("Back", "Index", "Home")
<div class="panel panel-default">
    <div class="panel-heading">Name: @Model.Name</div>
    <div class="panel-body">Phone: @Model.Phone</div>
    <div class="panel-body">Age: @Model.Age</div>
    <div class="panel-body">Address: @Model.Address</div>
</div>

Assignment_AppDev/Views/Trainers/Edit.cshtml
@model Assignment_AppDev.Models.Trainer
@{
    ViewBag.Title = "Edit";
}

<h2>Edit Trainer</h2>
@Html.ActionLink("Back", "Index")
@Html.ValidationSummary(false, "", new { @class = "text-danger" })
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(p => p.ID)


    <div class="form-group">
        @Html.LabelFor(t => t.Name)
        @Html.EditorFor(t => t.Name, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(t => t.Name)
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.TrainerID)
        @Html.EditorFor(p => p.TrainerID, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(p => p.TrainerID, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Age)
        @Html.EditorFor(p => p.Age, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(p => p.Age, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Phone)
        @Html.EditorFor(p => p.Phone, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(p => p.Phone, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Address)
        @Html.EditorFor(p => p.Address, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(p => p.Address, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
}

Assignment_AppDev/Views/Trainers/Index.cshtml
@model IEnumerable<Assignment_AppDev.Models.Trainer>

@{
    ViewBag.Title = "Index";
}

<h2>Trainer</h2>


@if (Request.IsAuthenticated && User.IsInRole("TrainingStaff"))
{

    @*<h3>Search Trainer</h3>
        using (@Html.BeginForm("Index", "Trainers", FormMethod.Get))
        {
            <p>
                Search by username: @Html.TextBox("SearchString")
                <input type="submit" value="Search" />
            </p>
        }*@
    @Html.ActionLink("Add Trainer Profile", "Create")


    <table class="table">
        <tr>


            @*<th>UserName</th>*@
            @*<th>Email</th>*@
            <th>FullName</th>
            <th>Age</th>
            <th>Phone</th>
            <th>Address</th>
            <th>Edit</th>
            <th>Delete</th>

        </tr>
        @foreach (var trainer in Model)
        {
            <tr>
                @*<th>trainer.Trainers.UserName</th>*@
                @*<th>trainer.Trainers.Email</th>*@
                <th>@trainer.Name</th>
                <th>@trainer.Age</th>
                <th>@trainer.Phone</th>
                <th>@trainer.Address</th>
                <th>@Html.ActionLink("Edit", "Edit", new { id = trainer.ID })</th>
                <th>@Html.ActionLink("Delete", "Delete", new { id = trainer.ID })</th>
            </tr>
        }
    </table>}
@if (User.IsInRole("Trainer"))
{
    <table class="table">
        <tr>
            <th>FullName</th>
            <th>Age</th>
            <th>Phone</th>
            <th>Address</th>
            <th>Edit</th>

        </tr>
        @foreach (var trainer in Model)
        {
            <tr>
                <th>@trainer.Name</th>
                <th>@trainer.Age</th>
                <th>@trainer.Phone</th>
                <th>@trainer.Address</th>
                <th>@Html.ActionLink("Edit", "Edit", new { id = trainer.ID })</th>
            </tr>
        }
    </table>
}
@Html.ActionLink("Back", "Index", "Home")