Assignment_AppDev/Controllers/CoursesController.cs
using Assignment_AppDev.Models;
using Assignment_AppDev.Utils;
using Assignment_AppDev.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Assignment_AppDev.Controllers
{
	[Authorize(Roles = "TrainingStaff")]
	public class CoursesController : Controller
    {
        private ApplicationDbContext _context;
        public CoursesController()
        {
            _context = new ApplicationDbContext();
        }
		// GET: Courses
		[HttpGet]
		public ActionResult Index(string searchString)
        {
			var courses = _context.Courses.Include(c => c.Category);

			if (!String.IsNullOrEmpty(searchString))
			{
						courses = courses.Where(
						s => s.Name.Contains(searchString) ||
						s.Category.Name.Contains(searchString));
			}

			return View(courses);
		}
		[HttpGet]
		public ActionResult Create()
		{
			var viewModel = new CourseCategoryViewModel
			{
				Categories = _context.Categories.ToList(),
				Course = new Course(),
			};
			return View(viewModel);
		}

		[HttpPost]
		public ActionResult Create(CourseCategoryViewModel coursecatee)
		{
			if (ModelState.IsValid)
			{
				var check = _context.Courses.Include(c => c.Category)
					.Where(c => c.Name == coursecatee.Course.Name && c.CategoryID == coursecatee.Course.CategoryID);

				//GET NameCourse and Category ID
				if (check.Count() > 0) //list ID comparison, if count == 0. jump to else
				{
                    ModelState.AddModelError("", "Course Already Exists.");
                }
				else
				{
					_context.Courses.Add(coursecatee.Course);
					_context.SaveChanges();
					return RedirectToAction("Index");
				}
			}
			var courseVM = new CourseCategoryViewModel()
			{
				Categories = _context.Categories.ToList(),
				Course = coursecatee.Course,
			};
			return View(courseVM);
		}
		[HttpGet]
		public ActionResult Edit(int id)
		{
			var courseInDb = _context.Courses.SingleOrDefault(c => c.ID == id);
			if (courseInDb == null)
			{
				return HttpNotFound();
			}
			var viewModel = new CourseCategoryViewModel
			{
				Course = courseInDb,
				Categories = _context.Categories.ToList()
			};
			return View(viewModel);
		}
		[HttpPost]
		public ActionResult Edit(CourseCategoryViewModel edit)
		{
			if (ModelState.IsValid)
			{
				var check = _context.Courses.Include(c => c.Category).Where(c => c.Name == edit.Course.Name && c.CategoryID == edit.Course.CategoryID);

				if (check.Count() > 0)
				{
					ModelState.AddModelError("", "Course Already Exists.");
				}
				else
				{
					var courseInDb = _context.Courses.Find(edit.Course.ID);
					courseInDb.Name = edit.Course.Name;
					courseInDb.Description = edit.Course.Description;
					_context.SaveChanges();
					return RedirectToAction("Index");
				}
			}

			var courseVM = new CourseCategoryViewModel()
			{
				Categories = _context.Categories.ToList(),
				Course = edit.Course,
			};
			return View(courseVM);
		}
		[HttpGet]
		public ActionResult Delete(int id)
		{
			var courseInDb = _context.Courses.SingleOrDefault(c => c.ID == id);

			if (courseInDb == null)
			{
				return HttpNotFound();
			}
			_context.Courses.Remove(courseInDb);
			_context.SaveChanges();
			return RedirectToAction("Index");
		}
	}
}

Assignment_AppDev/Controllers/TraineesController.cs
using Assignment_AppDev.Models;
using Assignment_AppDev.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
namespace Assingment_AppDev.Controllers
{
    public class TraineesController : Controller
    {
        private ApplicationDbContext _context;
        public TraineesController()
        {
            _context = new ApplicationDbContext();
        }
        [HttpGet]
        [Authorize(Roles = "TrainingStaff, Trainee")]

        public ActionResult Index(string searchString)
        {
            var trainee = _context.Trainees.Include(te => te.TraineeUser);
            if (!String.IsNullOrEmpty(searchString))
            {
                trainee = trainee.Where(s => s.TraineeUser.UserName.Contains(searchString));
                return View(trainee);
            }

            if (User.IsInRole("TrainingStaff"))
            {
                var viewTrainee = _context.Trainees.Include(a => a.TraineeUser).ToList();
                return View(viewTrainee);
            }
            if (User.IsInRole("Trainee"))
            {
                var traineeId = User.Identity.GetUserId();  
                var traineeVM = _context.Trainees.Where(te => te.TraineeID == traineeId).ToList();
                return View(traineeVM);
            }
            return View("Index");
        }
        [HttpGet]
        public ActionResult Details(int id)
        {
            var trainee = _context.Trainees.SingleOrDefault(t => t.Id == id);
            if (trainee == null)
            {
                return HttpNotFound();
            }

            return View(trainee);
        }
        [HttpGet]
        [Authorize(Roles = "TrainingStaff")]
        public ActionResult Create()
        {
            //Get Account Trainee
            var userInDb = (from r in _context.Roles where r.Name.Contains("Trainee") select r).FirstOrDefault();
            var users = _context.Users.Where(x => x.Roles.Select(y => y.RoleId).Contains(userInDb.Id)).ToList();
            var traineeUser = _context.Trainees.ToList();
            var viewModel = new TraineeViewModel
            {
                Trainees = users,
                Trainee = new Trainee()
            };
            return View(viewModel);
        }
        [HttpPost]
        [Authorize(Roles = "TrainingStaff")]
        public ActionResult Create(TraineeViewModel Traineeee)
        {
            var traineeinDb = (from te in _context.Roles where te.Name.Contains("Trainer") select te).FirstOrDefault();
            var traineeUser = _context.Users.Where(u => u.Roles.Select(us => us.RoleId).Contains(traineeinDb.Id)).ToList();
            try
            {
                _context.Trainees.Add(Traineeee.Trainee);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                TraineeViewModel traineeUserView = new TraineeViewModel()
                {
                    Trainees = traineeUser,
                    Trainee = Traineeee.Trainee
                };

                return View(traineeUserView);
            }


            //var traineeinDb = (from te in _context.Roles where te.Name.Contains("Trainee") select te).FirstOrDefault();
            //var traineeUser = _context.Users.Where(u => u.Roles.Select(us => us.RoleId).Contains(traineeinDb.Id)).ToList();
            //if (ModelState.IsValid)
            //{

            //    var checkTraineeExist = _context.Trainees.Include(t => t.TraineeUser).Where(t => t.TraineeUser.Id == Traineeee.Trainee.TraineeID);
            //    //GET TraineeID 
            //    if (checkTraineeExist.Count() > 0)  //list ID comparison, if count == 0. jump to else
            //    {
            //        ModelState.AddModelError("", "Trainee Already Exists.");
            //    }
            //    else
            //    {
            //        _context.Trainees.Add(Traineeee.Trainee);
            //        _context.SaveChanges();
            //        return RedirectToAction("Index");
            //    }
            //}
            //TraineeViewModel traineeUserView = new TraineeViewModel()
            //{
            //    Trainees = traineeUser,
            //    Trainee = Traineeee.Trainee
            //};
            //return View(traineeUserView);

        }
        [HttpGet]
        [Authorize(Roles = "TrainingStaff")]
        public ActionResult Delete(int id)
        {
            var todo = _context.Trainees.SingleOrDefault(t => t.Id == id);
            if (todo == null)
            {
                return HttpNotFound();
            }

            _context.Trainees.Remove(todo);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
        [HttpGet]
        [Authorize(Roles = "TrainingStaff,Trainee")]
        public ActionResult Edit(int id)
        {
            var trainee = _context.Trainees.SingleOrDefault(t => t.Id == id);
            if (trainee == null)
            {
                return HttpNotFound();
            }

            return View(trainee);
        }
        [HttpPost]
        [Authorize(Roles = "TrainingStaff, Trainee")]
        public ActionResult Edit(Trainee trainee)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var traineeInDb = _context.Trainees.SingleOrDefault(te => te.Id == trainee.Id);
            if (traineeInDb == null)
            {
                return HttpNotFound();
            }
            traineeInDb.Email = trainee.Email;
            traineeInDb.Name = trainee.Name;
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
     
    }
}

Assignment_AppDev/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application Name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Create Staff Account", "CreateStaffAccount", "Admin")</li>
                        <li>@Html.ActionLink("Create Trainer Account", "CreateTrainerAccount", "Admin")</li>
                        <li>@Html.ActionLink("Show Staff Information", "ShowStaffsInfo", "Admin")</li>
                        <li>@Html.ActionLink("Show Trainer Information", "ShowTrainersInfo", "Admin")</li>
                    }
                    @if (Request.IsAuthenticated && User.IsInRole("TrainingStaff"))
                    {
                        <li>@Html.ActionLink("Category", "Index", "Categories")</li>
                        <li>@Html.ActionLink("Course", "Index", "Courses")</li>
                        <li>@Html.ActionLink("Create Trainee Account", "CreateTraineeAccount", "StaffsViewModels")</li>
                        <li>@Html.ActionLink("Trainee Course", "Index", "AssignTraineeToCourses")</li>
                        <li>@Html.ActionLink("Trainer Course", "Index", "AssignTrainerToCourses")</li>
                        <li>@Html.ActionLink("Trainee", "Index", "Trainees")</li>
                        <li>@Html.ActionLink("Trainer", "Index", "Trainers")</li>
                        <li>@Html.ActionLink("View User", "Index", "StaffsViewModels")</li>
                    }
                    @if (Request.IsAuthenticated && User.IsInRole("Trainee"))
                    {
                        <li>@Html.ActionLink("Trainee", "Index", "Trainees")</li>
                        <li>@Html.ActionLink("Trainee Course", "Index", "AssignTraineetoCourses")</li>
                    }
                    @if (Request.IsAuthenticated && User.IsInRole("Trainer"))
                    {
                        <li>@Html.ActionLink("Trainer", "Index", "Trainers")</li>
                        <li>@Html.ActionLink("Trainer Course", "Index", "AssignTrainerToCourses")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>